import React from 'react';
import { motion } from 'framer-motion';
import { useInView } from 'react-intersection-observer';

const projects = [
  {
    title: 'Quiz App',
    description: ' A fun and interactive quiz application built with React and Tailwind CSS.',
    link: 'https://quiz-git-main-dipanshudeep-s-projects.vercel.app/ ',
  },
  {
    title: 'Todo List',
    description:' A simple and efficient todo list application built with React and Tailwind CSS.',
    link: 'https://07router-dm34.vercel.app/ ',
  },
  {
    title: ' Currency converter ',
    description: 'A simple currency converter application built with React and Tailwind CSS.',
    link: 'https://10todo.vercel.app/',
  },
  {
    title: 'Password Generator',
    description: 'A secure password generator application built with React and Tailwind CSS.',
    link: 'https://05passwordgen.vercel.app/ ',
  },
  {
    title: 'Background color changer ',
    description: ' A simple background color changer application built with React and Tailwind CSS.',
    link: 'https://04bgchanger-seven.vercel.app/',
  },
  {
    title: 'BMI Calculator ',
    description: 'A simple BMI calculator application built with html, CSS and JavaScript.',
    link: 'https://dipanshudeep.github.io/BMI_calculater/',
  },
  {
    title: 'Guess the number',
    description: 'A fun game where you guess a random number generated by the computer.',
    link: 'https://dipanshudeep.github.io/guss_the_number/',
  },
  {
    title: 'Color changer',
    description: 'A simple application that changes the body color on button click.',
    link: 'https://dipanshudeep.github.io/body_color_change/',
  },
  // Add more projects as needed
];

const Projects = () => {
  const [ref, inView] = useInView({
    triggerOnce: true,   // animation triggers only once
    threshold: 0.1,       // trigger when 10% of the component is visible
  });

  return (
    <div
      ref={ref}
      className='min-h-screen w-full bg-gradient-to-r from-gray-900 to-amber-950 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 p-4 sm:p-6 pt-24'
    >
      {projects.map((project, index) => (
        <motion.div
          key={index}
          initial={{ opacity: 0, y: 50 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6, delay: index * 0.2 }}
          className='pt-20'
        >
          <div className='bg-white/30 backdrop-blur-sm shadow-2xl ring-2 ring-black/20 rounded-3xl p-4 sm:p-6 hover:scale-105 transition-transform duration-300 flex flex-col '>
            <h2 className='text-xl sm:text-2xl font-bold mb-2 sm:mb-4 text-white'>{project.title}</h2>
            <p className='text-gray-300 mb-2 sm:mb-4 text-base sm:text-lg'>{project.description}</p>
            <a
              href={project.link}
              target='_blank'
              rel='noopener noreferrer'
              className='text-amber-500 hover:text-amber-300 transition-colors duration-300 mt-auto'
            >
              View Project
            </a>
          </div>
        </motion.div>
      ))}
    </div>
  );
};

export default Projects;
